import 'dotenv/config'
import { getPayload } from 'payload'
import config from '../payload.config'
import { ACCOUNTING_COLLECTION_SLUGS } from '../accounting/constants/accounting'

async function seedReversalEntries() {
  const payload = await getPayload({ config })

  console.log('[seed] Seeding Reversal Entries...')

  // Find some posted journal entries to reverse
  const postedEntries = await payload.find({
    collection: ACCOUNTING_COLLECTION_SLUGS.journalEntries,
    where: { status: { equals: 'posted' } },
    limit: 15,
    overrideAccess: true,
  })

  if (postedEntries.docs.length < 5) {
    console.warn('[seed] Not enough posted journal entries found to create reversal entries. Creating mock entries first...')
  }

  // Get some valid accounts to use for lines
  const accountsRes = await payload.find({
    collection: ACCOUNTING_COLLECTION_SLUGS.chartOfAccounts,
    limit: 2,
    overrideAccess: true,
  })

  if (accountsRes.docs.length < 2) {
    console.error('[seed] Not enough accounts found to create balanced entries. Run seed:journal-entry-lines first.')
    process.exit(1)
  }

  const account1 = accountsRes.docs[0].id
  const account2 = accountsRes.docs[1].id

  // If we don't have enough posted entries, create some dummy ones
  const baseEntriesIds: (number | string)[] = postedEntries.docs.map(d => d.id)

  for (let i = baseEntriesIds.length; i < 15; i++) {
    const dummy = await payload.create({
      collection: ACCOUNTING_COLLECTION_SLUGS.journalEntries,
      overrideAccess: true,
      data: {
        entryDate: new Date().toISOString(),
        postingDate: new Date().toISOString(),
        sourceType: 'manual',
        sourceReference: `DUMMY-POSTED-${i}`,
        memo: `Dummy posted entry ${i} for reversal testing`,
        status: 'draft',
      } as never,
    })
    
    // add lines for dummy entry
    await payload.create({
      collection: ACCOUNTING_COLLECTION_SLUGS.journalEntryLines,
      overrideAccess: true,
      data: {
        journalEntry: dummy.id,
        lineNumber: 1,
        account: account1,
        description: `Line 1`,
        debit: 100,
        credit: 0,
      } as never,
    })
    await payload.create({
      collection: ACCOUNTING_COLLECTION_SLUGS.journalEntryLines,
      overrideAccess: true,
      data: {
        journalEntry: dummy.id,
        lineNumber: 2,
        account: account2,
        description: `Line 2`,
        debit: 0,
        credit: 100,
      } as never,
    })

    await payload.update({
      collection: ACCOUNTING_COLLECTION_SLUGS.journalEntries,
      id: dummy.id,
      overrideAccess: true,
      data: { status: 'posted' } as never,
    })

    baseEntriesIds.push(dummy.id)
  }

  const sampleReversals = []
  for (let index = 0; index < 15; index++) {
    const isPosted = index % 3 === 0 // every 3rd is posted
    const targetEntryId = baseEntriesIds[index]
    
    // get original entry lines
    const originalLines = await payload.find({
      collection: ACCOUNTING_COLLECTION_SLUGS.journalEntryLines,
      where: { journalEntry: { equals: targetEntryId } },
      overrideAccess: true,
      limit: 100,
    })

    sampleReversals.push({
      sourceReference: `REV-NEW-00${index + 1}`,
      memo: `Reversal of entry ${targetEntryId}`,
      status: isPosted ? 'posted' : 'draft',
      reversalOf: targetEntryId,
      lines: originalLines.docs.map(l => ({
        account: typeof l.account === 'object' ? l.account.id : l.account,
        debit: l.credit || 0,
        credit: l.debit || 0,
      }))
    })
  }

  let created = 0
  let updated = 0

  for (const entry of sampleReversals) {
    // Check if header exists
    const existing = await payload.find({
      collection: ACCOUNTING_COLLECTION_SLUGS.journalEntries,
      where: { sourceReference: { equals: entry.sourceReference } },
      overrideAccess: true,
      depth: 0,
      limit: 1,
    })

    const targetStatus = entry.status
    const headerData = {
      entryDate: new Date().toISOString(),
      postingDate: new Date().toISOString(),
      sourceType: 'reversal',
      sourceReference: entry.sourceReference,
      memo: entry.memo,
      reversalOf: entry.reversalOf,
      status: 'draft',
      notes: `Generated by reversal entries seeder`,
    } as never

    let journalEntryId: number | string
    let existingStatus = ''

    if (existing.docs.length > 0) {
      const existingEntry = existing.docs[0] as unknown as Record<string, unknown>
      journalEntryId = existingEntry.id as number | string
      existingStatus = String(existingEntry.status || '')
      if (['posted', 'reversed', 'voided'].includes(existingStatus)) {
        console.log(`[seed] Skipping ${entry.sourceReference}: status is ${existingStatus}`)
        continue
      }
      await payload.update({
        collection: ACCOUNTING_COLLECTION_SLUGS.journalEntries,
        id: journalEntryId,
        overrideAccess: true,
        data: headerData,
      })
      updated++
    } else {
      const createdHeader = await payload.create({
        collection: ACCOUNTING_COLLECTION_SLUGS.journalEntries,
        overrideAccess: true,
        data: headerData,
      })
      journalEntryId = createdHeader.id
      created++
    }

    // Clear existing lines for this journal entry if draft
    if (existingStatus !== 'posted' && existingStatus !== 'reversed' && existingStatus !== 'voided') {
      const existingLines = await payload.find({
        collection: ACCOUNTING_COLLECTION_SLUGS.journalEntryLines,
        where: { journalEntry: { equals: journalEntryId } },
        overrideAccess: true,
        limit: 100,
      })

      for (const line of existingLines.docs) {
        await payload.delete({
          collection: ACCOUNTING_COLLECTION_SLUGS.journalEntryLines,
          id: line.id,
          overrideAccess: true,
        })
      }

      // Create lines
      for (let i = 0; i < entry.lines.length; i++) {
        const line = entry.lines[i]
        await payload.create({
          collection: ACCOUNTING_COLLECTION_SLUGS.journalEntryLines,
          overrideAccess: true,
          data: {
            journalEntry: journalEntryId,
            lineNumber: i + 1,
            account: line.account,
            description: `Line ${i + 1} for ${entry.sourceReference}`,
            debit: line.debit,
            credit: line.credit,
          } as never,
        })
      }

      // If the target status is 'posted', update it now that lines exist
      if (targetStatus === 'posted') {
        await payload.update({
          collection: ACCOUNTING_COLLECTION_SLUGS.journalEntries,
          id: journalEntryId,
          overrideAccess: true,
          data: {
            status: 'posted',
          } as never,
        })
      }
    }
  }

  console.log(`[seed] Done. Created: ${created}, Updated: ${updated}`)
  process.exit(0)
}

seedReversalEntries().catch((error) => {
  console.error('[seed] Fatal error:', error)
  process.exit(1)
})
