'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { AlertCircle, ArrowDownRight, ArrowUpRight, Download, Edit, Eye, Filter, Plus, RefreshCw, Search, Trash2, Wallet, X } from 'lucide-react';
import { getTimesheets, getTimesheetDetail, createTimesheet, updateTimesheet, deleteTimesheet, type TimesheetsResponse, type TimesheetDetail, type TmMetric } from './actions';

type FilterState = { statuses: string[] };

function getActionClasses(v: 'primary' | 'secondary' | 'ghost' = 'secondary') { if (v === 'primary') return 'border border-blue-600 bg-blue-600 text-white hover:bg-blue-700 hover:border-blue-700'; if (v === 'ghost') return 'border border-transparent bg-transparent text-gray-600 hover:bg-gray-100 hover:text-gray-900'; return 'border border-gray-300 bg-white text-gray-700 hover:bg-gray-50'; }
function getMetricTone(t: TmMetric['trend']) { if (t === 'down') return 'text-red-600 bg-red-50'; if (t === 'neutral') return 'text-gray-600 bg-gray-100'; return 'text-green-600 bg-green-50'; }
function escapeCsvValue(v: string | number | boolean | null | undefined) { const s = String(v ?? ''); return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s; }
function toggleFilterValue(values: string[], value: string) { return values.includes(value) ? values.filter((v) => v !== value) : [...values, value]; }

function SlideOver({ isOpen, onClose, title, description, children }: { isOpen: boolean; onClose: () => void; title: string; description?: string; children: React.ReactNode }) {
  const [mounted, setMounted] = useState(false); const [animate, setAnimate] = useState(false);
  useEffect(() => { if (isOpen) { setMounted(true); requestAnimationFrame(() => requestAnimationFrame(() => setAnimate(true))); } else { setAnimate(false); const timer = setTimeout(() => setMounted(false), 300); return () => clearTimeout(timer); } }, [isOpen]);
  if (!mounted) return null;
  return createPortal(<div className={`fixed inset-0 z-50 flex justify-end transition-opacity duration-300 ease-in-out ${animate ? 'bg-black/50' : 'bg-transparent'}`} onClick={onClose}><div className={`flex w-full max-w-lg flex-col bg-white shadow-xl transition-all duration-300 ease-in-out ${animate ? 'translate-x-0' : 'translate-x-full'}`} onClick={(e) => e.stopPropagation()}><div className="flex shrink-0 items-center justify-between border-b border-gray-200 px-6 py-4"><div><h3 className="text-lg font-semibold text-gray-900">{title}</h3>{description && <p className="mt-0.5 text-sm text-gray-500">{description}</p>}</div><button type="button" onClick={onClose} className="rounded-lg p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600"><X className="h-5 w-5" /></button></div><div className="flex-1 overflow-y-auto px-6 py-4">{children}</div></div></div>, document.body);
}

function FormField({ label, children, required }: { label: string; children: React.ReactNode; required?: boolean }) { return <div className="space-y-1.5"><label className="block text-sm font-medium text-gray-700">{label}{required && <span className="ml-0.5 text-red-500">*</span>}</label>{children}</div>; }
function Input({ value, onChange, placeholder, type = 'text', required }: { value: string; onChange: (v: string) => void; placeholder?: string; type?: string; required?: boolean }) { return <input type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} required={required} className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100" />; }
function Select({ value, onChange, options }: { value: string; onChange: (v: string) => void; options: Array<{ label: string; value: string }> }) { return <select value={value} onChange={(e) => onChange(e.target.value)} className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100">{options.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select>; }
function TextArea({ value, onChange, rows = 3 }: { value: string; onChange: (v: string) => void; rows?: number }) { return <textarea value={value} onChange={(e) => onChange(e.target.value)} rows={rows} className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100" />; }

function MetricCard({ label, value, change, trend = 'neutral' }: { label: string; value: string | number; change: string; trend?: 'up' | 'down' | 'neutral' }) { const TrendIcon = trend === 'down' ? ArrowDownRight : ArrowUpRight; return <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-gray-500">{label}</p><p className="mt-3 text-2xl font-bold text-gray-900">{value}</p></div><div className="rounded-lg bg-gray-100 p-3 text-gray-600"><Wallet className="h-5 w-5" /></div></div><div className="mt-4 flex items-center gap-2"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-medium ${getMetricTone(trend)}`}><TrendIcon className="h-3.5 w-3.5" />{change}</span></div></div>; }
function LoadingSkeleton() { return <div className="space-y-4"><div className="overflow-hidden rounded-xl border border-gray-200"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr>{Array.from({ length: 5 }).map((_, i) => <th key={i} className="px-4 py-3"><div className="h-4 w-24 animate-pulse rounded bg-gray-200" /></th>)}</tr></thead><tbody className="divide-y divide-gray-200 bg-white">{Array.from({ length: 5 }).map((_, i) => (<tr key={i}><td colSpan={5} className="px-4 py-3"><div className="h-6 animate-pulse rounded bg-gray-100" /></td></tr>))}</tbody></table></div></div></div>; }

function renderCell(cell: string | { text: string; tone?: string; emphasis?: boolean; align?: string }, index: number) {
  if (typeof cell === 'string') return <td key={index} className="whitespace-nowrap px-4 py-3 text-sm text-gray-600">{cell}</td>;
  const ac = cell.align === 'right' ? 'text-right' : cell.align === 'center' ? 'text-center' : 'text-left';
  if (cell.tone) { const t: Record<string, string> = { amber: 'bg-amber-50 text-amber-700 ring-amber-200', green: 'bg-green-50 text-green-700 ring-green-200', gray: 'bg-gray-100 text-gray-700 ring-gray-200', blue: 'bg-blue-50 text-blue-700 ring-blue-200', red: 'bg-red-50 text-red-700 ring-red-200' }; return <td key={index} className={`whitespace-nowrap px-4 py-3 text-sm ${ac}`}><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ring-1 ring-inset ${t[cell.tone] || t.gray}`}>{cell.text}</span></td>; }
  return <td key={index} className={`whitespace-nowrap px-4 py-3 text-sm ${cell.emphasis ? 'font-semibold text-gray-900' : 'text-gray-600'} ${ac}`}>{cell.text}</td>;
}

type Form = { userId: string; periodStart: string; periodEnd: string; status: string; notes: string };
function empty(): Form { return { userId: '', periodStart: '', periodEnd: '', status: 'draft', notes: '' }; }
function build(d: TimesheetDetail): Form { return { userId: d.userId || '', periodStart: d.periodStart ? d.periodStart.slice(0, 10) : '', periodEnd: d.periodEnd ? d.periodEnd.slice(0, 10) : '', status: d.status || 'draft', notes: d.notes || '' }; }

export function TimesheetsClient() {
  const [data, setData] = useState<TimesheetsResponse | null>(null);
  const [error, setError] = useState<string | null>(null); const [isLoading, setIsLoading] = useState(false);
  const [searchInput, setSearchInput] = useState(''); const [submittedSearch, setSubmittedSearch] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [filters, setFilters] = useState<FilterState>({ statuses: [] });
  const [quickFilters, setQuickFilters] = useState<string[]>([]);
  const [draftFilters, setDraftFilters] = useState<FilterState>({ statuses: [] });
  const [isFilterPanelOpen, setIsFilterPanelOpen] = useState(false);
  const fc = filters.statuses.length;

  const [isCreateOpen, setIsCreateOpen] = useState(false); const [isCreateSubmitting, setIsCreateSubmitting] = useState(false); const [createErr, setCreateErr] = useState<string | null>(null);
  const [form, setForm] = useState<Form>(empty());
  const [viewDetail, setViewDetail] = useState<TimesheetDetail | null>(null); const [isViewOpen, setIsViewOpen] = useState(false); const [isViewLoading, setIsViewLoading] = useState(false);
  const [editId, setEditId] = useState<string | null>(null); const [isEditOpen, setIsEditOpen] = useState(false); const [isEditSubmitting, setIsEditSubmitting] = useState(false); const [editErr, setEditErr] = useState<string | null>(null);
  const [deleteId, setDeleteId] = useState<string | null>(null); const [deleteLabel, setDeleteLabel] = useState(''); const [isDeleteOpen, setIsDeleteOpen] = useState(false); const [isDeleteSubmitting, setIsDeleteSubmitting] = useState(false); const [deleteErr, setDeleteErr] = useState<string | null>(null);

  const fetchData = useCallback(async ({ s, p, nf, nq }: { s: string; p: number; nf: FilterState; nq: string[] }) => { setIsLoading(true); setError(null); try { setData(await getTimesheets({ search: s, page: p, statuses: nf.statuses, quickFilters: nq })); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load timesheets.'); } finally { setIsLoading(false); } }, []);
  useEffect(() => { void fetchData({ s: submittedSearch, p: currentPage, nf: filters, nq: quickFilters }); }, [filters, currentPage, quickFilters, submittedSearch, fetchData]);

  const handleSearch = (e: React.FormEvent) => { e.preventDefault(); setSubmittedSearch(searchInput); setCurrentPage(1); fetchData({ s: searchInput, p: 1, nf: filters, nq: quickFilters }); };
  const handleRefresh = () => { fetchData({ s: submittedSearch, p: currentPage, nf: filters, nq: quickFilters }); };
  const handleToggleQuickFilter = (v: string) => { setQuickFilters((p) => toggleFilterValue(p, v)); setCurrentPage(1); };
  const handleExport = () => { const rows = data?.section.table.rows; if (!rows?.length) return; const h = ['Period Start', 'Period End', 'User', 'Total Hours', 'Status']; const c = [h.map(escapeCsvValue), ...rows.map((r) => [r.periodStartLabel, r.periodEndLabel, r.userLabel, r.totalHoursLabel, r.statusLabel].map(escapeCsvValue))].map((r) => r.join(',')).join('\n'); const b = new Blob([c], { type: 'text/csv;charset=utf-8;' }); const u = URL.createObjectURL(b); const l = document.createElement('a'); l.href = u; l.download = 'timesheets.csv'; document.body.appendChild(l); l.click(); document.body.removeChild(l); URL.revokeObjectURL(u); };

  const handleOpenCreate = () => { setForm(empty()); setCreateErr(null); setIsCreateOpen(true); };
  const submitCreate = async (e: React.FormEvent) => { e.preventDefault(); setCreateErr(null); setIsCreateSubmitting(true); try { await createTimesheet({ userId: form.userId, periodStart: form.periodStart, periodEnd: form.periodEnd, status: form.status, notes: form.notes || undefined }); setIsCreateOpen(false); handleRefresh(); } catch (err) { setCreateErr(err instanceof Error ? err.message : 'An error occurred'); } finally { setIsCreateSubmitting(false); } };

  const handleView = async (id: string) => { setIsViewOpen(true); setIsViewLoading(true); setViewDetail(null); try { setViewDetail(await getTimesheetDetail(id)); } catch (e) { console.error(e); } finally { setIsViewLoading(false); } };
  const handleOpenEdit = async (id: string) => { setIsEditOpen(true); setEditErr(null); setEditId(id); setIsViewLoading(true); setViewDetail(null); try { const d = await getTimesheetDetail(id); setViewDetail(d); setForm(build(d)); } catch (e) { setEditErr(e instanceof Error ? e.message : 'Unable to load details.'); } finally { setIsViewLoading(false); } };
  const submitEdit = async (e: React.FormEvent) => { e.preventDefault(); if (!editId) return; setEditErr(null); setIsEditSubmitting(true); try { await updateTimesheet(editId, { userId: form.userId, periodStart: form.periodStart, periodEnd: form.periodEnd, status: form.status, notes: form.notes || undefined }); setIsEditOpen(false); handleRefresh(); } catch (err) { setEditErr(err instanceof Error ? err.message : 'An error occurred'); } finally { setIsEditSubmitting(false); } };

  const handleOpenDelete = (id: string, label: string) => { setDeleteId(id); setDeleteLabel(label); setIsDeleteOpen(true); setDeleteErr(null); };
  const handleConfirmDelete = async () => { if (!deleteId) return; setIsDeleteSubmitting(true); setDeleteErr(null); try { await deleteTimesheet(deleteId); setIsDeleteOpen(false); handleRefresh(); } catch (err) { setDeleteErr(err instanceof Error ? err.message : 'Unable to delete.'); } finally { setIsDeleteSubmitting(false); } };

  const rd = data?.referenceData;
  const userOpts = [{ label: 'Select a user', value: '' }, ...(rd?.users || []).map((u) => ({ label: u.label, value: u.id }))];
  const stOpts = rd?.statusOptions || [];

  const rf = () => (<>
    <div className="grid grid-cols-2 gap-4">
      <FormField label="Period Start" required><Input type="date" value={form.periodStart} onChange={(v) => setForm({ ...form, periodStart: v })} required /></FormField>
      <FormField label="Period End" required><Input type="date" value={form.periodEnd} onChange={(v) => setForm({ ...form, periodEnd: v })} required /></FormField>
    </div>
    <FormField label="User" required><Select value={form.userId} onChange={(v) => setForm({ ...form, userId: v })} options={userOpts} /></FormField>
    <FormField label="Status" required><Select value={form.status} onChange={(v) => setForm({ ...form, status: v })} options={stOpts} /></FormField>
    <FormField label="Notes"><TextArea value={form.notes} onChange={(v) => setForm({ ...form, notes: v })} rows={2} /></FormField>
  </>);

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 rounded-xl border border-gray-200 bg-gray-50 p-5 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex flex-col gap-1"><h2 className="text-lg font-semibold text-gray-900">Timesheets</h2><p className="text-sm text-gray-600">Review timesheet containers grouping time entries by user and period for submission and approval.</p><p className="text-sm text-gray-500">{data?.totals.filteredRows ?? 0} matching rows</p></div>
        <div className="flex flex-wrap items-center gap-2"><button type="button" onClick={handleRefresh} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors ${getActionClasses('secondary')}`}><RefreshCw className="h-4 w-4" /> Refresh</button><button type="button" onClick={handleOpenCreate} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors ${getActionClasses('primary')}`}><Plus className="h-4 w-4" /> New Timesheet</button></div>
      </div>

      {data?.section.metrics && data.section.metrics.length > 0 ? (<div className="grid grid-cols-1 gap-4 lg:grid-cols-2 xl:grid-cols-4">{data.section.metrics.map((m) => (<div key={m.id}><MetricCard label={m.label} value={m.value} change={m.change} trend={m.trend} /></div>))}</div>) : null}

      <div className="rounded-xl border border-gray-200 bg-white shadow-sm">
        <div className="flex flex-col gap-4 border-b border-gray-200 px-5 py-4 lg:flex-row lg:items-center lg:justify-between">
          <div className="flex flex-1 flex-col gap-3 lg:flex-row lg:items-center"><form onSubmit={handleSearch} className="flex min-w-0 max-w-xl flex-1 gap-3"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input type="text" placeholder={data?.section.searchPlaceholder || 'Search timesheets'} value={searchInput} onChange={(e) => setSearchInput(e.target.value)} className="w-full rounded-lg border border-gray-300 bg-white py-2.5 pl-10 pr-4 text-sm text-gray-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div><button type="submit" className="inline-flex items-center gap-2 rounded-lg border border-blue-600 bg-blue-600 px-4 py-2.5 text-sm font-medium text-white transition-colors hover:border-blue-700 hover:bg-blue-700"><Search className="h-4 w-4" /> Search</button></form><button type="button" onClick={() => { if (!isFilterPanelOpen) setDraftFilters({ ...filters }); setIsFilterPanelOpen((p) => !p); }} className={`inline-flex items-center gap-2 rounded-lg border px-4 py-2.5 text-sm font-medium transition-colors ${isFilterPanelOpen || fc > 0 ? 'border-blue-200 bg-blue-50 text-blue-700 hover:bg-blue-100' : 'border-gray-300 bg-white text-gray-700 hover:bg-gray-50'}`}><Filter className="h-4 w-4" /> Filters{fc > 0 && <span className="inline-flex min-w-5 items-center justify-center rounded-full bg-blue-600 px-1.5 py-0.5 text-[11px] font-semibold text-white">{fc}</span>}</button></div>
          <div className="flex flex-wrap gap-2">{(() => { const qf = data?.section?.filters?.quickFilters; if (qf && qf.length > 0) return qf.map((f) => <button key={f.value} type="button" onClick={() => handleToggleQuickFilter(f.value)} className={`rounded-full px-3 py-1.5 text-xs font-medium transition-colors ${quickFilters.includes(f.value) ? 'bg-blue-50 text-blue-700 ring-1 ring-inset ring-blue-200' : 'bg-gray-100 text-gray-700 hover:bg-gray-200'}`}>{f.label}</button>); return null; })()}</div>
        </div>
        <div className="space-y-4 p-[10px] sm:p-5">
          {isFilterPanelOpen && (<div className="rounded-xl border border-gray-200 bg-gray-50 p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><h4 className="text-sm font-semibold text-gray-900">Filters</h4><p className="mt-1 text-sm text-gray-600">Select as many filter values as needed, then apply them in one step.</p></div><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={() => { setDraftFilters({ statuses: [] }); setFilters({ statuses: [] }); setCurrentPage(1); setIsFilterPanelOpen(false); }} className="text-sm font-medium text-gray-500 hover:text-gray-700">Clear all</button><button type="button" onClick={() => { setDraftFilters({ ...filters }); setIsFilterPanelOpen(false); }} className="rounded-lg border border-gray-300 bg-white px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50">Cancel</button><button type="button" onClick={() => { setFilters({ ...draftFilters }); setCurrentPage(1); setIsFilterPanelOpen(false); }} className="rounded-lg border border-blue-600 bg-blue-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-700">Apply Filters</button></div></div><div className="mt-6"><h5 className="text-xs font-semibold uppercase tracking-wider text-gray-500">Status</h5><div className="mt-3 flex flex-wrap gap-2">{(data?.section?.filters?.statuses || []).map((o) => { const s = draftFilters.statuses.includes(o.value); return <button key={o.value} type="button" onClick={() => setDraftFilters((p) => ({ ...p, statuses: toggleFilterValue(p.statuses, o.value) }))} className={`rounded-full px-3 py-1.5 text-xs font-medium transition-colors ${s ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 ring-1 ring-inset ring-gray-300 hover:bg-gray-100'}`}>{o.label}</button>; })}</div></div></div>)}
          <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="space-y-2"><h3 className="text-base font-semibold text-gray-900">Timesheet Register</h3><p className="text-sm text-gray-600">Timesheet containers aligned to accounting-timesheets, showing period, user, status, and total hours.</p></div><div className="flex flex-wrap items-center gap-3 text-sm text-gray-500"><span>{data?.totals.filteredRows ?? 0} matching rows</span><button type="button" onClick={handleExport} disabled={!(data?.section.table.rows.length)} className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"><Download className="h-4 w-4" /> Download View</button></div></div>
          {error && <div className="flex items-center gap-2 rounded-lg bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="h-4 w-4 shrink-0" />{error}</div>}
          {isLoading ? <LoadingSkeleton /> : (<>
            <div className="overflow-hidden rounded-xl border border-gray-200"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr><th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">Period Start</th><th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">Period End</th><th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">User</th><th className="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wider text-gray-500">Total Hours</th><th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">Status</th><th className="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wider text-gray-500">Actions</th></tr></thead><tbody className="divide-y divide-gray-200 bg-white">{(data?.section.table.rows ?? []).length > 0 ? (data?.section.table.rows ?? []).map((row) => (<tr key={row.id} className="hover:bg-gray-50">{row.cells.map((cell, index) => renderCell(cell, index))}<td className="px-4 py-3 text-right"><div className="flex justify-end gap-2"><button type="button" onClick={() => handleView(row.id)} className="inline-flex items-center gap-1 rounded-lg p-2 text-gray-500 transition-colors hover:bg-gray-100 hover:text-gray-700" title="View"><Eye className="h-4 w-4" /></button><button type="button" onClick={() => handleOpenEdit(row.id)} className="inline-flex items-center gap-1 rounded-lg p-2 text-gray-500 transition-colors hover:bg-gray-100 hover:text-gray-700" title="Edit"><Edit className="h-4 w-4" /></button><button type="button" onClick={() => handleOpenDelete(row.id, row.periodStartLabel)} className="inline-flex items-center gap-1 rounded-lg p-2 text-red-500 transition-colors hover:bg-red-50 hover:text-red-700" title="Delete"><Trash2 className="h-4 w-4" /></button></div></td></tr>)) : (<tr><td colSpan={6} className="px-4 py-10 text-center text-sm text-gray-500">No timesheets found.</td></tr>)}</tbody></table></div></div>
            {data?.pagination && data.pagination.totalPages > 1 && (<div className="flex items-center justify-between"><p className="text-sm text-gray-600">Page {data.pagination.page} of {data.pagination.totalPages}</p><div className="flex gap-2"><button type="button" disabled={!data.pagination.hasPrevPage} onClick={() => setCurrentPage((p) => Math.max(1, p - 1))} className="rounded-lg border border-gray-300 bg-white px-3 py-1.5 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 disabled:opacity-50">Previous</button><button type="button" disabled={!data.pagination.hasNextPage} onClick={() => setCurrentPage((p) => p + 1)} className="rounded-lg border border-gray-300 bg-white px-3 py-1.5 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 disabled:opacity-50">Next</button></div></div>)}
          </>)}
        </div>
      </div>

      <SlideOver isOpen={isCreateOpen} onClose={() => setIsCreateOpen(false)} title="New Timesheet" description="Create a timesheet container for a user and period."><form onSubmit={submitCreate} className="space-y-6">{createErr && <div className="flex items-center gap-2 rounded-lg bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="h-4 w-4 shrink-0" />{createErr}</div>}{rf()}<div className="flex items-center justify-end gap-3 border-t border-gray-200 pt-4"><button type="button" onClick={() => setIsCreateOpen(false)} disabled={isCreateSubmitting} className="rounded-lg px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 disabled:opacity-50">Cancel</button><button type="submit" disabled={isCreateSubmitting} className={`rounded-lg px-4 py-2 text-sm font-medium text-white transition-colors disabled:opacity-50 ${getActionClasses('primary')}`}>{isCreateSubmitting ? 'Creating...' : 'Create Timesheet'}</button></div></form></SlideOver>

      <SlideOver isOpen={isViewOpen} onClose={() => setIsViewOpen(false)} title="Timesheet Detail" description="View full timesheet record."><div className="space-y-6">{isViewLoading ? <LoadingSkeleton /> : viewDetail ? (<div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm space-y-4">
        <div className="flex justify-between border-b pb-3"><span className="text-sm text-gray-500">Period Start</span><span className="text-sm font-medium text-gray-900">{viewDetail.periodStartLabel}</span></div>
        <div className="flex justify-between border-b pb-3"><span className="text-sm text-gray-500">Period End</span><span className="text-sm font-medium text-gray-900">{viewDetail.periodEndLabel}</span></div>
        <div className="flex justify-between border-b pb-3"><span className="text-sm text-gray-500">User</span><span className="text-sm font-medium text-gray-900">{viewDetail.userLabel}</span></div>
        <div className="flex justify-between border-b pb-3"><span className="text-sm text-gray-500">Total Hours</span><span className="text-sm font-medium text-gray-900">{viewDetail.totalHours.toFixed(2)}</span></div>
        <div className="flex justify-between border-b pb-3"><span className="text-sm text-gray-500">Status</span><span className="text-sm font-medium text-gray-900">{viewDetail.status}</span></div>
        <div className="flex justify-between border-b pb-3"><span className="text-sm text-gray-500">Approved By</span><span className="text-sm font-medium text-gray-900">{viewDetail.approvedByLabel}</span></div>
        <div className="flex justify-between"><span className="text-sm text-gray-500">Notes</span><span className="text-right text-sm font-medium text-gray-900">{viewDetail.notes || '-'}</span></div>
      </div>) : <p className="text-sm text-gray-500">No details available.</p>}<div className="flex justify-end pt-4"><button type="button" onClick={() => setIsViewOpen(false)} className="rounded-lg bg-gray-100 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-200">Close</button></div></div></SlideOver>

      <SlideOver isOpen={isEditOpen} onClose={() => setIsEditOpen(false)} title="Edit Timesheet" description="Modify the timesheet."><form onSubmit={submitEdit} className="space-y-6">{isViewLoading ? <LoadingSkeleton /> : <>{editErr && <div className="flex items-center gap-2 rounded-lg bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="h-4 w-4 shrink-0" />{editErr}</div>}{rf()}<div className="flex items-center justify-end gap-3 border-t border-gray-200 pt-4"><button type="button" onClick={() => setIsEditOpen(false)} disabled={isEditSubmitting} className="rounded-lg px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 disabled:opacity-50">Cancel</button><button type="submit" disabled={isEditSubmitting} className={`rounded-lg px-4 py-2 text-sm font-medium text-white transition-colors disabled:opacity-50 ${getActionClasses('primary')}`}>{isEditSubmitting ? 'Saving...' : 'Save Changes'}</button></div></>}</form></SlideOver>

      <SlideOver isOpen={isDeleteOpen} onClose={() => { setIsDeleteOpen(false); setDeleteId(null); }} title="Delete Timesheet" description="Remove this timesheet permanently."><div className="space-y-6">{deleteErr && <div className="flex items-center gap-2 rounded-lg bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="h-4 w-4 shrink-0" />{deleteErr}</div>}<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><p className="font-medium">Are you sure?</p><p className="mt-1">Timesheet starting {deleteLabel} will be permanently removed. If time entries are linked, deletion will be blocked.</p></div><div className="flex justify-end gap-3 border-t border-gray-200 pt-4"><button type="button" onClick={() => { setIsDeleteOpen(false); setDeleteId(null); }} disabled={isDeleteSubmitting} className="rounded-lg bg-gray-100 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-200 disabled:opacity-50">Cancel</button><button type="button" onClick={handleConfirmDelete} disabled={isDeleteSubmitting} className="rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700 disabled:opacity-50">{isDeleteSubmitting ? 'Deleting...' : 'Delete Timesheet'}</button></div></div></SlideOver>
    </div>
  );
}
