/**
 * @encreasl/cms-types - Shared CMS Types Package
 * 
 * Provides TypeScript types and schemas for Payload CMS collections
 * shared across the Encreasl monorepo.
 */

// ========================================
// PAYLOAD CMS TYPES
// ========================================

// Re-export Payload types from the CMS app
// Note: These types should be generated by Payload CMS
export interface Post {
  id: string;
  title: string;
  slug: string;
  content?: any;
  excerpt?: string;
  featuredImage?: Media | string;
  status: 'draft' | 'published';
  publishedAt?: string;
  author: User | string | null;
  tags?: Array<{ tag: string }>;
  seo?: {
    title?: string;
    description?: string;
    focusKeyword?: string;
  };
  updatedAt: string;
  createdAt: string;
}

export interface Media {
  id: string;
  url?: string;
  filename: string;
  alt?: string;
  mimeType?: string;
  filesize?: number;
  updatedAt: string;
  createdAt: string;
}

export interface User {
  id: string;
  email: string;
  firstName?: string;
  lastName?: string;
  updatedAt: string;
  createdAt: string;
}

export interface Service {
  id: string;
  title: string;
  description?: string;
  updatedAt: string;
  createdAt: string;
}

export interface Config {
  collections: any[];
  globals: any[];
}

export type CourseDifficultyLevel = 'standard' | 'intermediate' | 'advanced';

export type CourseLanguage = 'en' | 'es' | 'fr' | 'de';

export type CourseStatus = 'draft' | 'published' | 'archived';

export type EvaluationMode = 'lessons' | 'exam' | 'quizzes' | 'lessons_exam' | 'lessons_quizzes' | 'quizzes_exam' | 'lessons_quizzes_exam';

export type DurationUnit = 'minutes' | 'hours' | 'days' | 'weeks';

export interface InstructorRef {
  id: string;
  user?: {
    id: string;
    firstName?: string;
    lastName?: string;
    email?: string;
  };
}

export interface CategoryRef {
  id: string;
  name?: string;
  title?: string;
}

export interface MediaRef {
  id: string;
  url?: string;
  cloudinaryURL?: string;
  filename?: string;
  alt?: string;
}

export interface SimpleDocRef {
  id: string;
  title?: string;
  name?: string;
}

export interface Course {
  id: string;
  title: string;
  courseCode: string;
  excerpt?: string;
  description?: any;
  descriptionBlocks?: ContentBlock[];
  instructor: InstructorRef | string;
  coInstructors?: (InstructorRef | string)[];
  category?: (CategoryRef | string)[];
  modules?: (SimpleDocRef | string)[];
  thumbnail?: MediaRef | string;
  bannerImage?: MediaRef | string;
  price: number;
  discountedPrice?: number;
  maxStudents?: number;
  enrollmentStartDate?: string;
  enrollmentEndDate?: string;
  courseStartDate?: string;
  courseEndDate?: string;
  estimatedDuration?: number;
  estimatedDurationUnit?: DurationUnit;
  difficultyLevel: CourseDifficultyLevel;
  isFeatured: boolean;
  language: CourseLanguage;
  passingGrade: number;
  gradeScale?: SimpleDocRef | string;
  evaluationMode: EvaluationMode;
  learningObjectives?: Array<{ objective: string }>;
  prerequisites?: Array<{ prerequisite: string }>;
  certificateTemplate?: SimpleDocRef | string;
  feedbackForm?: SimpleDocRef | string;
  isFeedbackRequired?: boolean;
  status: CourseStatus;
  publishedAt?: string;
  settings?: Record<string, unknown>;
  updatedAt: string;
  createdAt: string;
}

export interface CourseListResult {
  docs: Course[];
  totalDocs: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface CategoryOption {
  id: string;
  name: string;
}

// ========================================
// ENROLLMENT TYPES
// ========================================

export type EnrollmentStatus = 'active' | 'pending' | 'suspended' | 'dropped' | 'completed' | 'expired';

export interface EnrollmentStudentRef {
  id: string;
  user: {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
  };
  srn?: string;
}

export interface EnrollmentCourseRef {
  id: string;
  title: string;
  courseCode: string;
  status?: string;
}

export interface EnrollmentDoc {
  id: string;
  student: EnrollmentStudentRef;
  course: EnrollmentCourseRef;
  status: string;
  enrollmentType: string;
  enrolledAt: string;
  progressPercentage: number;
  completedAt?: string | null;
  notes: string;
}

export interface EnrollmentListResult {
  docs: EnrollmentDoc[];
  totalDocs: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface CourseOption {
  id: string;
  title: string;
  courseCode: string;
  status?: string;
}

export interface TraineeOption {
  id: string;
  user: {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
  };
  srn: string;
}

export interface EnrollmentFilters {
  search?: string;
  status?: string;
  page?: number;
  limit?: number;
  userId?: string;
}

export interface CreateEnrollmentInput {
  student: string;
  course: string;
  notes?: string;
  status?: string;
  userId?: string;
}

export interface CourseEditData {
  course: Course;
  categories: CategoryOption[];
  modules?: SimpleDocRef[];
}

export interface CourseModule {
  id: string;
  title: string;
  course: Course | string;
   description?: any;
  order: number;
  releaseAt?: string;
  updatedAt: string;
  createdAt: string;
}

export interface CourseLesson {
  id: string;
  title: string;
  module: CourseModule | string;
  order: number;
  bodyBlocks?: ContentBlock[];
  estimatedDuration?: number;
  updatedAt: string;
  createdAt: string;
}

export type MaterialSource = 'media' | 'external';

export interface Material {
  id: string;
  title: string;
  description?: string;
  materialSource: MaterialSource;
  media?: Media | string | (Media | string)[] | null;
  externalUrl?: string;
  metadata?: Record<string, unknown>;
  updatedAt: string;
  createdAt: string;
}

export interface Announcement {
  id: string;
  title: string;
  course: Course | string;
  bodyBlocks?: ContentBlock[];
  pinned: boolean;
  visibleFrom?: string;
  visibleUntil?: string;
  createdBy?: User | string;
  updatedAt: string;
  createdAt: string;
}

export type BlockType = 'heading' | 'paragraph' | 'list' | 'image' | 'quote' | 'code';

export interface HeadingBlock {
  type: 'heading';
  level: 1 | 2 | 3 | 4;
  text: string;
}

export interface ParagraphBlock {
  type: 'paragraph';
  text: string;
}

export interface ListBlock {
  type: 'list';
  style: 'ordered' | 'unordered';
  items: string[];
}

export interface ImageBlock {
  type: 'image';
  url: string;
  alt?: string;
  caption?: string;
  width?: string;
  height?: string;
}

export interface QuoteBlock {
  type: 'quote';
  text: string;
  attribution?: string;
}

export interface CodeBlock {
  type: 'code';
  language?: string;
  code: string;
}

export type ContentBlock =
  | HeadingBlock
  | ParagraphBlock
  | ListBlock
  | ImageBlock
  | QuoteBlock
  | CodeBlock;

export type QuizQuestionType = 'single_choice' | 'multiple_choice' | 'true_false';

export interface QuizQuestionOption {
  id: string;
  label: string;
  isCorrect: boolean;
}

export interface QuizQuestion {
  id: string;
  type: QuizQuestionType;
  prompt: string;
  explanation?: string;
  difficulty: 'easy' | 'medium' | 'hard';
  status: 'draft' | 'active' | 'deprecated';
  tags?: string[];
  options: QuizQuestionOption[];
}

export interface Assessment {
  id: string;
  title: string;
  module: CourseModule | string;
  order: number;
  description?: any;
  isRequired: boolean;
  estimatedDuration?: number;
  passMark: number;
  maxAttempts: number;
  items: Array<{
    question: QuizQuestion | string;
    order?: number;
    points?: number;
  }>;
  updatedAt: string;
  createdAt: string;
}

// ========================================
// CUSTOM TYPES
// ========================================

export interface PostFormData {
  title: string;
  slug: string;
  content: any; // Lexical editor state
  excerpt?: string;
  featuredImage?: number; // Media ID as number to match Payload
  status: 'draft' | 'published';
  publishedAt?: string;
  author: number; // User ID as number to match Payload
  tags?: Array<{ tag: string; id?: string }>;
  seo?: {
    title?: string;
    description?: string;
    focusKeyword?: string;
  };
}

export interface MediaUploadData {
  file: File;
  alt: string;
}

export interface PostListItem {
  id: string;
  title: string;
  slug: string;
  status: 'draft' | 'published';
  publishedAt?: string;
  updatedAt: string;
  author: {
    id: string;
    email: string;
    firstName?: string;
    lastName?: string;
  };
  featuredImage?: {
    id: string;
    url: string;
    alt: string;
  };
}

export interface PostFilters {
  status?: 'draft' | 'published';
  author?: string;
  search?: string;
  limit?: number;
  page?: number;
}

// ========================================
// API RESPONSE TYPES
// ========================================

export interface CMSApiResponse<T = any> {
  docs?: T[];
  doc?: T;
  totalDocs?: number;
  limit?: number;
  page?: number;
  totalPages?: number;
  hasNextPage?: boolean;
  hasPrevPage?: boolean;
  errors?: Array<{
    message: string;
    field?: string;
  }>;
}

export interface CMSError {
  message: string;
  status?: number;
  field?: string;
}

// ========================================
// VALIDATION SCHEMAS
// ========================================

export * from './schemas';
export * from './api';
export * from './course-api';
