'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { AlertCircle, ArrowDownRight, ArrowUpRight, Download, Eye, Filter, RefreshCw, Search, Wallet, X } from 'lucide-react';
import { getBudgetVsActual, getVarianceDetail, type BvaResponse, type VarianceDetail, type BvaMetric } from './actions';

type FilterState = { statuses: string[] };

function getActionClasses(v: 'primary' | 'secondary' | 'ghost' = 'secondary') { if (v === 'primary') return 'border border-blue-600 bg-blue-600 text-white hover:bg-blue-700 hover:border-blue-700'; if (v === 'ghost') return 'border border-transparent bg-transparent text-gray-600 hover:bg-gray-100 hover:text-gray-900'; return 'border border-gray-300 bg-white text-gray-700 hover:bg-gray-50'; }
function getMetricTone(t: BvaMetric['trend']) { if (t === 'down') return 'text-red-600 bg-red-50'; if (t === 'neutral') return 'text-gray-600 bg-gray-100'; return 'text-green-600 bg-green-50'; }
function escapeCsvValue(v: string | number | boolean | null | undefined) { const s = String(v ?? ''); return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s; }
function toggleFilterValue(values: string[], value: string) { return values.includes(value) ? values.filter((v) => v !== value) : [...values, value]; }
function fmtCurrency(n: number) { return `PHP ${n.toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

function SlideOver({ isOpen, onClose, title, description, children }: { isOpen: boolean; onClose: () => void; title: string; description?: string; children: React.ReactNode }) {
  const [mounted, setMounted] = useState(false); const [animate, setAnimate] = useState(false);
  useEffect(() => { if (isOpen) { setMounted(true); requestAnimationFrame(() => requestAnimationFrame(() => setAnimate(true))); } else { setAnimate(false); const timer = setTimeout(() => setMounted(false), 300); return () => clearTimeout(timer); } }, [isOpen]);
  if (!mounted) return null;
  return createPortal(<div className={`fixed inset-0 z-50 flex justify-end transition-opacity duration-300 ease-in-out ${animate ? 'bg-black/50' : 'bg-transparent'}`} onClick={onClose}><div className={`flex w-full max-w-lg flex-col bg-white shadow-xl transition-all duration-300 ease-in-out ${animate ? 'translate-x-0' : 'translate-x-full'}`} onClick={(e) => e.stopPropagation()}><div className="flex shrink-0 items-center justify-between border-b border-gray-200 px-6 py-4"><div><h3 className="text-lg font-semibold text-gray-900">{title}</h3>{description && <p className="mt-0.5 text-sm text-gray-500">{description}</p>}</div><button type="button" onClick={onClose} className="rounded-lg p-1 text-gray-400 hover:bg-gray-100 hover:text-gray-600"><X className="h-5 w-5" /></button></div><div className="flex-1 overflow-y-auto px-6 py-4">{children}</div></div></div>, document.body);
}

function MetricCard({ label, value, change, trend = 'neutral' }: { label: string; value: string | number; change: string; trend?: 'up' | 'down' | 'neutral' }) { const TrendIcon = trend === 'down' ? ArrowDownRight : ArrowUpRight; return <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-gray-500">{label}</p><p className="mt-3 text-2xl font-bold text-gray-900">{value}</p></div><div className="rounded-lg bg-gray-100 p-3 text-gray-600"><Wallet className="h-5 w-5" /></div></div><div className="mt-4 flex items-center gap-2"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-medium ${getMetricTone(trend)}`}><TrendIcon className="h-3.5 w-3.5" />{change}</span></div></div>; }
function LoadingSkeleton() { return <div className="space-y-4"><div className="overflow-hidden rounded-xl border border-gray-200"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr>{Array.from({ length: 6 }).map((_, i) => <th key={i} className="px-4 py-3"><div className="h-4 w-24 animate-pulse rounded bg-gray-200" /></th>)}</tr></thead><tbody className="divide-y divide-gray-200 bg-white">{Array.from({ length: 5 }).map((_, i) => (<tr key={i}><td colSpan={6} className="px-4 py-3"><div className="h-6 animate-pulse rounded bg-gray-100" /></td></tr>))}</tbody></table></div></div></div>; }

function renderCell(cell: string | { text: string; tone?: string; emphasis?: boolean; align?: string }, index: number) {
  if (typeof cell === 'string') return <td key={index} className="whitespace-nowrap px-4 py-3 text-sm text-gray-600">{cell}</td>;
  const ac = cell.align === 'right' ? 'text-right' : cell.align === 'center' ? 'text-center' : 'text-left';
  if (cell.tone) { const t: Record<string, string> = { amber: 'bg-amber-50 text-amber-700 ring-amber-200', green: 'bg-green-50 text-green-700 ring-green-200', gray: 'bg-gray-100 text-gray-700 ring-gray-200', blue: 'bg-blue-50 text-blue-700 ring-blue-200', red: 'bg-red-50 text-red-700 ring-red-200' }; return <td key={index} className={`whitespace-nowrap px-4 py-3 text-sm ${ac}`}><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ring-1 ring-inset ${t[cell.tone] || t.gray}`}>{cell.text}</span></td>; }
  return <td key={index} className={`whitespace-nowrap px-4 py-3 text-sm ${cell.emphasis ? 'font-semibold text-gray-900' : 'text-gray-600'} ${ac}`}>{cell.text}</td>;
}

export function BudgetVsActualClient() {
  const [data, setData] = useState<BvaResponse | null>(null);
  const [error, setError] = useState<string | null>(null); const [isLoading, setIsLoading] = useState(false);
  const [searchInput, setSearchInput] = useState(''); const [submittedSearch, setSubmittedSearch] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [filters, setFilters] = useState<FilterState>({ statuses: [] });
  const [quickFilters, setQuickFilters] = useState<string[]>([]);
  const [draftFilters, setDraftFilters] = useState<FilterState>({ statuses: [] });
  const [isFilterPanelOpen, setIsFilterPanelOpen] = useState(false); const fc = filters.statuses.length;

  const [viewDetail, setViewDetail] = useState<VarianceDetail | null>(null); const [isViewOpen, setIsViewOpen] = useState(false); const [isViewLoading, setIsViewLoading] = useState(false);

  const doFetch = useCallback(async ({ s, p, nf, nq }: { s: string; p: number; nf: FilterState; nq: string[] }) => { setIsLoading(true); setError(null); try { setData(await getBudgetVsActual({ search: s, page: p, statuses: nf.statuses, quickFilters: nq })); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load.'); } finally { setIsLoading(false); } }, []);
  useEffect(() => { void doFetch({ s: submittedSearch, p: currentPage, nf: filters, nq: quickFilters }); }, [filters, currentPage, quickFilters, submittedSearch, doFetch]);

  const handleSearch = (e: React.FormEvent) => { e.preventDefault(); setSubmittedSearch(searchInput); setCurrentPage(1); doFetch({ s: searchInput, p: 1, nf: filters, nq: quickFilters }); };
  const handleRefresh = () => { doFetch({ s: submittedSearch, p: currentPage, nf: filters, nq: quickFilters }); };
  const handleToggleQuickFilter = (v: string) => { setQuickFilters((p) => toggleFilterValue(p, v)); setCurrentPage(1); };
  const handleExport = () => { const rows = data?.section.table.rows; if (!rows?.length) return; const h = ['Budget Code', 'Scope', 'Budget Amount', 'Actual Amount', 'Variance', 'Status']; const c = [h.map(escapeCsvValue), ...rows.map((r) => [r.budgetCode, r.scope, fmtCurrency(r.budgetAmount), fmtCurrency(r.actualAmount), fmtCurrency(r.varianceAmount), r.varianceStatus].map(escapeCsvValue))].map((r) => r.join(',')).join('\n'); const b = new Blob([c], { type: 'text/csv;charset=utf-8;' }); const u = URL.createObjectURL(b); const l = document.createElement('a'); l.href = u; l.download = 'budget-vs-actual.csv'; document.body.appendChild(l); l.click(); document.body.removeChild(l); URL.revokeObjectURL(u); };

  const handleView = async (id: string) => { setIsViewOpen(true); setIsViewLoading(true); setViewDetail(null); try { setViewDetail(await getVarianceDetail(id)); } catch (e) { console.error(e); } finally { setIsViewLoading(false); } };

  return (<div className="space-y-6 p-[10px]">
    <div className="flex flex-col gap-4 rounded-xl border border-gray-200 bg-gray-50 p-5 lg:flex-row lg:items-center lg:justify-between">
      <div className="flex flex-col gap-1"><h2 className="text-lg font-semibold text-gray-900">Budget vs Actual</h2><p className="text-sm text-gray-600">Review budget-variance output backed by accounting budgets and the budget-variance service.</p><p className="text-sm text-gray-500">{data?.totals.filteredRows ?? 0} matching rows</p></div>
      <div className="flex flex-wrap items-center gap-2"><button type="button" onClick={handleRefresh} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors ${getActionClasses('secondary')}`}><RefreshCw className="h-4 w-4" /> Refresh</button></div>
    </div>

    {data?.section.metrics && data.section.metrics.length > 0 ? (<div className="grid grid-cols-1 gap-4 lg:grid-cols-2 xl:grid-cols-4">{data.section.metrics.map((m) => (<div key={m.id}><MetricCard label={m.label} value={m.value} change={m.change} trend={m.trend} /></div>))}</div>) : null}

    <div className="rounded-xl border border-gray-200 bg-white shadow-sm">
      <div className="flex flex-col gap-4 border-b border-gray-200 px-5 py-4 lg:flex-row lg:items-center lg:justify-between">
        <div className="flex flex-1 flex-col gap-3 lg:flex-row lg:items-center"><form onSubmit={handleSearch} className="flex min-w-0 max-w-xl flex-1 gap-3"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input type="text" placeholder={data?.section.searchPlaceholder || 'Search variance'} value={searchInput} onChange={(e) => setSearchInput(e.target.value)} className="w-full rounded-lg border border-gray-300 bg-white py-2.5 pl-10 pr-4 text-sm text-gray-900 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div><button type="submit" className="inline-flex items-center gap-2 rounded-lg border border-blue-600 bg-blue-600 px-4 py-2.5 text-sm font-medium text-white transition-colors hover:border-blue-700 hover:bg-blue-700"><Search className="h-4 w-4" /> Search</button></form><button type="button" onClick={() => { if (!isFilterPanelOpen) setDraftFilters({ ...filters }); setIsFilterPanelOpen((p) => !p); }} className={`inline-flex items-center gap-2 rounded-lg border px-4 py-2.5 text-sm font-medium transition-colors ${isFilterPanelOpen || fc > 0 ? 'border-blue-200 bg-blue-50 text-blue-700 hover:bg-blue-100' : 'border-gray-300 bg-white text-gray-700 hover:bg-gray-50'}`}><Filter className="h-4 w-4" /> Filters{fc > 0 && <span className="inline-flex min-w-5 items-center justify-center rounded-full bg-blue-600 px-1.5 py-0.5 text-[11px] font-semibold text-white">{fc}</span>}</button></div>
        <div className="flex flex-wrap gap-2">{(() => { const qf = data?.section?.filters?.quickFilters; if (qf && qf.length > 0) return qf.map((f) => <button key={f.value} type="button" onClick={() => handleToggleQuickFilter(f.value)} className={`rounded-full px-3 py-1.5 text-xs font-medium transition-colors ${quickFilters.includes(f.value) ? 'bg-blue-50 text-blue-700 ring-1 ring-inset ring-blue-200' : 'bg-gray-100 text-gray-700 hover:bg-gray-200'}`}>{f.label}</button>); return null; })()}</div>
      </div>
      <div className="space-y-4 p-[10px] sm:p-5">
        {isFilterPanelOpen && (<div className="rounded-xl border border-gray-200 bg-gray-50 p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><h4 className="text-sm font-semibold text-gray-900">Filters</h4><p className="mt-1 text-sm text-gray-600">Select as many filter values as needed, then apply them in one step.</p></div><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={() => { setDraftFilters({ statuses: [] }); setFilters({ statuses: [] }); setCurrentPage(1); setIsFilterPanelOpen(false); }} className="text-sm font-medium text-gray-500 hover:text-gray-700">Clear all</button><button type="button" onClick={() => { setDraftFilters({ ...filters }); setIsFilterPanelOpen(false); }} className="rounded-lg border border-gray-300 bg-white px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50">Cancel</button><button type="button" onClick={() => { setFilters({ ...draftFilters }); setCurrentPage(1); setIsFilterPanelOpen(false); }} className="rounded-lg border border-blue-600 bg-blue-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-blue-700">Apply Filters</button></div></div><div className="mt-6"><h5 className="text-xs font-semibold uppercase tracking-wider text-gray-500">Status</h5><div className="mt-3 flex flex-wrap gap-2">{(data?.section?.filters?.statuses || []).map((o) => { const s = draftFilters.statuses.includes(o.value); return <button key={o.value} type="button" onClick={() => setDraftFilters((p) => ({ ...p, statuses: toggleFilterValue(p.statuses, o.value) }))} className={`rounded-full px-3 py-1.5 text-xs font-medium transition-colors ${s ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 ring-1 ring-inset ring-gray-300 hover:bg-gray-100'}`}>{o.label}</button>; })}</div></div></div>)}
        <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="space-y-2"><h3 className="text-base font-semibold text-gray-900">Budget vs Actual Analysis</h3><p className="text-sm text-gray-600">Budget variance view aligned to accounting budgets and the budget-variance service.</p></div><div className="flex flex-wrap items-center gap-3 text-sm text-gray-500"><span>{data?.totals.filteredRows ?? 0} matching rows</span><button type="button" onClick={handleExport} disabled={!(data?.section.table.rows.length)} className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"><Download className="h-4 w-4" /> Download View</button></div></div>
        {error && <div className="flex items-center gap-2 rounded-lg bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="h-4 w-4 shrink-0" />{error}</div>}
        {isLoading ? <LoadingSkeleton /> : (<>
          <div className="overflow-hidden rounded-xl border border-gray-200"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr><th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">Budget Code</th><th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">Scope</th><th className="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wider text-gray-500">Budget Amount</th><th className="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wider text-gray-500">Actual Amount</th><th className="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wider text-gray-500">Variance</th><th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-gray-500">Status</th><th className="px-4 py-3 text-right text-xs font-semibold uppercase tracking-wider text-gray-500">Actions</th></tr></thead><tbody className="divide-y divide-gray-200 bg-white">{(data?.section.table.rows ?? []).length > 0 ? (data?.section.table.rows ?? []).map((row) => (<tr key={row.id} className="hover:bg-gray-50">{row.cells.map((cell, index) => renderCell(cell, index))}<td className="px-4 py-3 text-right"><button type="button" onClick={() => handleView(row.budgetId)} className="inline-flex items-center gap-1 rounded-lg p-2 text-gray-500 transition-colors hover:bg-gray-100 hover:text-gray-700" title="View variance detail"><Eye className="h-4 w-4" /></button></td></tr>)) : (<tr><td colSpan={7} className="px-4 py-10 text-center text-sm text-gray-500">No variance data found.</td></tr>)}</tbody></table></div></div>
          {data?.pagination && data.pagination.totalPages > 1 && (<div className="flex items-center justify-between"><p className="text-sm text-gray-600">Page {data.pagination.page} of {data.pagination.totalPages}</p><div className="flex gap-2"><button type="button" disabled={!data.pagination.hasPrevPage} onClick={() => setCurrentPage((p) => Math.max(1, p - 1))} className="rounded-lg border border-gray-300 bg-white px-3 py-1.5 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 disabled:opacity-50">Previous</button><button type="button" disabled={!data.pagination.hasNextPage} onClick={() => setCurrentPage((p) => p + 1)} className="rounded-lg border border-gray-300 bg-white px-3 py-1.5 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 disabled:opacity-50">Next</button></div></div>)}
        </>)}
      </div>
    </div>

    <SlideOver isOpen={isViewOpen} onClose={() => setIsViewOpen(false)} title="Variance Detail" description="Line-by-line budget vs actual comparison for this budget.">
      <div className="space-y-6">{isViewLoading ? <LoadingSkeleton /> : viewDetail ? (<div className="space-y-6">
        <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm space-y-3">
          <div className="flex justify-between"><span className="text-sm text-gray-500">Budget</span><span className="text-sm font-medium text-gray-900">{viewDetail.budgetCode} - {viewDetail.name}</span></div>
          <div className="flex justify-between"><span className="text-sm text-gray-500">Status</span><span className="text-sm font-medium text-gray-900">{viewDetail.status}</span></div>
        </div>
        <div className="rounded-xl border border-blue-200 bg-blue-50 p-5 shadow-sm space-y-2">
          <h4 className="text-sm font-semibold text-blue-800">Summary</h4>
          <div className="flex justify-between"><span className="text-sm text-blue-700">Total Planned</span><span className="text-sm font-medium text-blue-900">{fmtCurrency(viewDetail.totals.plannedAmount)}</span></div>
          <div className="flex justify-between"><span className="text-sm text-blue-700">Total Actual</span><span className="text-sm font-medium text-blue-900">{fmtCurrency(viewDetail.totals.actualAmount)}</span></div>
          <div className="flex justify-between border-t border-blue-300 pt-2"><span className="text-sm font-semibold text-blue-800">Variance</span><span className={`text-sm font-semibold ${viewDetail.totals.varianceAmount >= 0 ? 'text-green-700' : 'text-red-700'}`}>{fmtCurrency(viewDetail.totals.varianceAmount)}</span></div>
        </div>
        {viewDetail.rows.length > 0 && (<div>
          <h4 className="text-sm font-semibold text-gray-900 mb-3">Line-by-Line Breakdown ({viewDetail.rows.length} lines)</h4>
          <div className="rounded-xl border border-gray-200 overflow-x-auto"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr><th className="px-3 py-2 text-left text-xs font-semibold text-gray-500">Account</th><th className="px-3 py-2 text-right text-xs font-semibold text-gray-500">Planned</th><th className="px-3 py-2 text-right text-xs font-semibold text-gray-500">Actual</th><th className="px-3 py-2 text-right text-xs font-semibold text-gray-500">Variance</th></tr></thead><tbody className="divide-y divide-gray-200 bg-white">{viewDetail.rows.map((r) => (<tr key={r.budgetLineId} className="hover:bg-gray-50"><td className="px-3 py-2 text-sm text-gray-600">{r.accountCode} - {r.accountName}</td><td className="px-3 py-2 text-right text-sm">{fmtCurrency(r.plannedAmount)}</td><td className="px-3 py-2 text-right text-sm">{fmtCurrency(r.actualAmount)}</td><td className={`px-3 py-2 text-right text-sm font-medium ${r.varianceAmount >= 0 ? 'text-green-600' : 'text-red-600'}`}>{fmtCurrency(r.varianceAmount)}</td></tr>))}</tbody></table></div>
        </div>)}
      </div>) : <p className="text-sm text-gray-500">No details.</p>}<div className="flex justify-end pt-4"><button type="button" onClick={() => setIsViewOpen(false)} className="rounded-lg bg-gray-100 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-200">Close</button></div></div>
    </SlideOver>
  </div>);
}
